### PR TITLE
config-6.12: add back some config-6.6 options

### PR DESCRIPTION
**Pull request by graysky2**
Tickless options[1] got missed on the 6.6 to 6.12 update.

Before this commit, booting into 6.12.1 gave idle CPU freq around ~1366 MHz compared to 400 MHz booted into 6.6.63. Idle power consumption was also up by approx 1 watt (6 W on 6.6.63 vs 7 W on 6.12.1).

After applying the commit both idle CPU freq and idle power consumption were the same (due to tickless kernel).

1. https://github.com/openwrt/openwrt/commit/31111680f6fc5f17201b02b8ce656b955be56d7a

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

### CODE REVIEW

**Comment by namiltd** [comment]
Some of the changed settings concern other things, e.g.:
```
-# CONFIG_DRM_DISPLAY_DP_AUX_CEC is not set
-# CONFIG_DRM_DISPLAY_DP_AUX_CHARDEV is not set
+CONFIG_DRM_BUDDY=y
+CONFIG_DRM_DISPLAY_DP_HELPER=y
+CONFIG_DRM_DISPLAY_HDCP_HELPER=y
+CONFIG_DRM_DISPLAY_HDMI_HELPER=y
+CONFIG_DRM_DISPLAY_HELPER=y
```
I would like this fix to only restore https://github.com/openwrt/openwrt/commit/31111680f6fc5f17201b02b8ce656b955be56d7a

**Comment by namiltd** [comment]
I have already included these changes about an hour ago.

**Comment by graysky2** [comment]
OK, plz close the PR if you incorporate in the future so I will avoid any double work.  Will you be adding back the other options I initially included or shall I do it and open a new PR?

**Comment by namiltd** [comment]
Add new PR for new options.

**Pull request closed without merging**
